# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-05-21 16:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Departments',
            new_name='Config',
        ),
        migrations.RenameModel(
            old_name='Configs',
            new_name='Department',
        ),
        migrations.RenameModel(
            old_name='Projects',
            new_name='Project',
        ),
        migrations.RenameModel(
            old_name='Users',
            new_name='User',
        ),
        migrations.RenameField(
            model_name='config',
            old_name='departmentName',
            new_name='configName',
        ),
        migrations.RenameField(
            model_name='department',
            old_name='configName',
            new_name='departmentName',
        ),
    ]
