# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-05-25 07:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20160521_1652'),
    ]

    operations = [
        migrations.AddField(
            model_name='config',
            name='projects',
            field=models.ManyToManyField(to='blog.Project'),
        ),
        migrations.AlterField(
            model_name='user',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Department'),
        ),
    ]
